version: "3.8"
services:
  next-app:
    build: .
    image: next-app
#    ports:
#      - "80:3000"
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - next-app
